# Generated by Django 3.2.13 on 2022-07-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_pricing_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
