# Generated by Django 3.2.13 on 2022-07-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_course_pricing_tiers'),
        ('bag', '0002_auto_20220711_1837'),
        ('accounts', '0004_alter_subscription_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='student',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
