# Generated by Django 3.2.13 on 2022-07-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_course_pricing_tiers'),
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_added']},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='pricing',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.course'),
        ),
    ]
