# Generated by Django 3.2.13 on 2022-07-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_auto_20220713_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
