# Generated by Django 3.2.13 on 2022-06-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220624_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to='categories/photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(upload_to='courses/thumbnails/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='lessons/photos/%Y/%m/%d/'),
        ),
    ]
