# Generated by Django 3.2.13 on 2022-07-03 16:27

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_section_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
