# Generated by Django 3.2.13 on 2022-07-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='dideoUrl',
        ),
    ]
