# Generated by Django 3.2.13 on 2022-07-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscription_student'),
        ('content', '0007_rename_dideourl_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pricing_tiers',
            field=models.ManyToManyField(blank=True, to='accounts.Pricing'),
        ),
    ]
