# Generated by Django 3.2.13 on 2022-07-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_course_pricing_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
