# Generated by Django 3.2.13 on 2022-07-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_alter_course_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_intro_url',
        ),
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
