# Generated by Django 3.2.13 on 2022-08-18 18:26

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_intro_url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
